// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"database/sql"
)

type Discofeature struct {
	ID  int64  `db:"id"`
	Var string `db:"var"`
}

type Discofeaturejid struct {
	ID   int64 `db:"id"`
	Jid  int64 `db:"jid"`
	Feat int64 `db:"feat"`
}

type Discoidentity struct {
	ID   int64  `db:"id"`
	Cat  string `db:"cat"`
	Name string `db:"name"`
	Typ  string `db:"typ"`
	Lang string `db:"lang"`
}

type Discoidentityjid struct {
	ID    int64 `db:"id"`
	Jid   int64 `db:"jid"`
	Ident int64 `db:"ident"`
}

type Discojid struct {
	ID    int64          `db:"id"`
	Jid   string         `db:"jid"`
	Caps  int64          `db:"caps"`
	Forms sql.NullString `db:"forms"`
}

type Entitycap struct {
	ID   int64  `db:"id"`
	Hash string `db:"hash"`
	Ver  string `db:"ver"`
}

type Localkeysalt struct {
	ID   bool   `db:"id"`
	Salt []byte `db:"salt"`
}

type Message struct {
	ID            int64          `db:"id"`
	Accountjid    string         `db:"accountjid"`
	Sent          bool           `db:"sent"`
	Toattr        sql.NullString `db:"toattr"`
	Fromattr      sql.NullString `db:"fromattr"`
	Idattr        sql.NullString `db:"idattr"`
	Body          sql.NullString `db:"body"`
	Encrypted     bool           `db:"encrypted"`
	Originid      sql.NullString `db:"originid"`
	Stanzatype    string         `db:"stanzatype"`
	Received      bool           `db:"received"`
	Delay         int64          `db:"delay"`
	Rosterjid     sql.NullString `db:"rosterjid"`
	Archiveid     sql.NullString `db:"archiveid"`
	Replytoidattr sql.NullString `db:"replytoidattr"`
	Retracted     bool           `db:"retracted"`
}

type Messagereaction struct {
	ID         int64  `db:"id"`
	Accountjid string `db:"accountjid"`
	Idattr     string `db:"idattr"`
	Fromjid    string `db:"fromjid"`
	Emoji      string `db:"emoji"`
}

type Pgppeerkey struct {
	Accountjid  string `db:"accountjid"`
	Jid         string `db:"jid"`
	Fingerprint string `db:"fingerprint"`
}

type Rostergroup struct {
	ID         int64  `db:"id"`
	Accountjid string `db:"accountjid"`
	Jid        string `db:"jid"`
	Name       string `db:"name"`
}

type Rosterjid struct {
	Accountjid string `db:"accountjid"`
	Jid        string `db:"jid"`
	Name       string `db:"name"`
	Subs       string `db:"subs"`
}

type Rosterver struct {
	Accountjid string `db:"accountjid"`
	Ver        string `db:"ver"`
}
