// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"database/sql"
)

type Callpeerfingerprint struct {
	Accountjid  string `db:"accountjid"`
	Jid         string `db:"jid"`
	Fingerprint string `db:"fingerprint"`
}

type Chatdraft struct {
	Accountjid string `db:"accountjid"`
	Rosterjid  string `db:"rosterjid"`
	Body       string `db:"body"`
	Encrypted  bool   `db:"encrypted"`
}

type Chatencryption struct {
	Accountjid string `db:"accountjid"`
	Rosterjid  string `db:"rosterjid"`
	Mode       string `db:"mode"`
}

type Chatunread struct {
	Accountjid string `db:"accountjid"`
	Rosterjid  string `db:"rosterjid"`
	Count      int64  `db:"count"`
}

type Discofeature struct {
	ID  int64  `db:"id"`
	Var string `db:"var"`
}

type Discofeaturejid struct {
	ID   int64 `db:"id"`
	Jid  int64 `db:"jid"`
	Feat int64 `db:"feat"`
}

type Discoidentity struct {
	ID   int64  `db:"id"`
	Cat  string `db:"cat"`
	Name string `db:"name"`
	Typ  string `db:"typ"`
	Lang string `db:"lang"`
}

type Discoidentityjid struct {
	ID    int64 `db:"id"`
	Jid   int64 `db:"jid"`
	Ident int64 `db:"ident"`
}

type Discojid struct {
	ID    int64          `db:"id"`
	Jid   string         `db:"jid"`
	Caps  int64          `db:"caps"`
	Forms sql.NullString `db:"forms"`
}

type Entitycap struct {
	ID   int64  `db:"id"`
	Hash string `db:"hash"`
	Ver  string `db:"ver"`
}

type Localkeysalt struct {
	ID   bool   `db:"id"`
	Salt []byte `db:"salt"`
}

type Mamsynccursor struct {
	Accountjid string `db:"accountjid"`
	Rosterjid  string `db:"rosterjid"`
	Archiveid  string `db:"archiveid"`
}

type Message struct {
	ID               int64          `db:"id"`
	Accountjid       string         `db:"accountjid"`
	Sent             bool           `db:"sent"`
	Toattr           sql.NullString `db:"toattr"`
	Fromattr         sql.NullString `db:"fromattr"`
	Idattr           sql.NullString `db:"idattr"`
	Body             sql.NullString `db:"body"`
	Encrypted        bool           `db:"encrypted"`
	E2eencrypted     bool           `db:"e2eencrypted"`
	E2eemethod       sql.NullString `db:"e2eemethod"`
	Originid         sql.NullString `db:"originid"`
	Stanzatype       string         `db:"stanzatype"`
	Received         bool           `db:"received"`
	Delay            int64          `db:"delay"`
	Rosterjid        sql.NullString `db:"rosterjid"`
	Archiveid        sql.NullString `db:"archiveid"`
	Replytoidattr    sql.NullString `db:"replytoidattr"`
	Retracted        bool           `db:"retracted"`
	Edited           bool           `db:"edited"`
	Delivered        bool           `db:"delivered"`
	Serveracked      bool           `db:"serveracked"`
	Sendfailed       bool           `db:"sendfailed"`
	Ooburls          sql.NullString `db:"ooburls"`
	Calldirection    sql.NullString `db:"calldirection"`
	Calloutcome      sql.NullString `db:"calloutcome"`
	Calldurationsecs sql.NullInt64  `db:"calldurationsecs"`
}

type Messagereaction struct {
	ID         int64  `db:"id"`
	Accountjid string `db:"accountjid"`
	Rosterjid  string `db:"rosterjid"`
	Idattr     string `db:"idattr"`
	Fromjid    string `db:"fromjid"`
	Emoji      string `db:"emoji"`
}

type Omemodevice struct {
	Accountjid string `db:"accountjid"`
	Protocol   string `db:"protocol"`
	Peerjid    string `db:"peerjid"`
	Deviceid   int64  `db:"deviceid"`
}

type Omemoidentity struct {
	Accountjid string `db:"accountjid"`
	Protocol   string `db:"protocol"`
	Privatekey []byte `db:"privatekey"`
	Deviceid   int64  `db:"deviceid"`
}

type Omemonextprekeyid struct {
	Accountjid string `db:"accountjid"`
	Protocol   string `db:"protocol"`
	Nextid     int64  `db:"nextid"`
}

type Omemopeerprotocol struct {
	Accountjid string `db:"accountjid"`
	Peerjid    string `db:"peerjid"`
	Protocol   string `db:"protocol"`
	Probedat   int64  `db:"probedat"`
}

type Omemoprekey struct {
	Accountjid string `db:"accountjid"`
	Protocol   string `db:"protocol"`
	ID         int64  `db:"id"`
	Public     []byte `db:"public"`
	Private    []byte `db:"private"`
}

type Omemoremoteidentity struct {
	Accountjid  string `db:"accountjid"`
	Protocol    string `db:"protocol"`
	Peerjid     string `db:"peerjid"`
	Deviceid    int64  `db:"deviceid"`
	Identitykey []byte `db:"identitykey"`
}

type Omemosession struct {
	Accountjid string `db:"accountjid"`
	Protocol   string `db:"protocol"`
	Peerjid    string `db:"peerjid"`
	Deviceid   int64  `db:"deviceid"`
	Data       []byte `db:"data"`
}

type Omemosignedprekey struct {
	Accountjid string `db:"accountjid"`
	Protocol   string `db:"protocol"`
	ID         int64  `db:"id"`
	Public     []byte `db:"public"`
	Private    []byte `db:"private"`
	Signature  []byte `db:"signature"`
	Stale      bool   `db:"stale"`
}

type Omemotrust struct {
	Accountjid  string `db:"accountjid"`
	Protocol    string `db:"protocol"`
	Identitykey []byte `db:"identitykey"`
	State       int64  `db:"state"`
}

type Outbox struct {
	ID               int64          `db:"id"`
	Accountjid       string         `db:"accountjid"`
	Localid          string         `db:"localid"`
	Toattr           string         `db:"toattr"`
	Body             string         `db:"body"`
	Encrypted        bool           `db:"encrypted"`
	Filepath         sql.NullString `db:"filepath"`
	Replaceid        sql.NullString `db:"replaceid"`
	Replytoid        sql.NullString `db:"replytoid"`
	Quotedauthor     sql.NullString `db:"quotedauthor"`
	Quotedbody       sql.NullString `db:"quotedbody"`
	Retractid        sql.NullString `db:"retractid"`
	Reactiontargetid sql.NullString `db:"reactiontargetid"`
	Reactions        sql.NullString `db:"reactions"`
	Ooburls          sql.NullString `db:"ooburls"`
	Createdat        int64          `db:"createdat"`
	Failed           bool           `db:"failed"`
	Errortext        sql.NullString `db:"errortext"`
}

type Pgppeerkey struct {
	Accountjid  string `db:"accountjid"`
	Jid         string `db:"jid"`
	Fingerprint string `db:"fingerprint"`
}

type Rostergroup struct {
	ID         int64  `db:"id"`
	Accountjid string `db:"accountjid"`
	Jid        string `db:"jid"`
	Name       string `db:"name"`
}

type Rosterjid struct {
	Accountjid string `db:"accountjid"`
	Jid        string `db:"jid"`
	Name       string `db:"name"`
	Subs       string `db:"subs"`
}

type Rosterver struct {
	Accountjid string `db:"accountjid"`
	Ver        string `db:"ver"`
}
