// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package storage

import (
	"context"
	"database/sql"
)

const consumeOmemoPreKey = `-- name: ConsumeOmemoPreKey :one
DELETE FROM omemoPreKey
WHERE accountJID = ?1 AND protocol = ?2 AND id = ?3
RETURNING id, public, private
`

type ConsumeOmemoPreKeyParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
	ID         int64  `db:"id"`
}

type ConsumeOmemoPreKeyRow struct {
	ID      int64  `db:"id"`
	Public  []byte `db:"public"`
	Private []byte `db:"private"`
}

func (q *Queries) ConsumeOmemoPreKey(ctx context.Context, arg ConsumeOmemoPreKeyParams) (ConsumeOmemoPreKeyRow, error) {
	row := q.db.QueryRowContext(ctx, consumeOmemoPreKey, arg.AccountJid, arg.Protocol, arg.ID)
	var i ConsumeOmemoPreKeyRow
	err := row.Scan(&i.ID, &i.Public, &i.Private)
	return i, err
}

const countOmemoPreKeys = `-- name: CountOmemoPreKeys :one
SELECT count(*)
FROM omemoPreKey
WHERE accountJID = ?1 AND protocol = ?2
`

type CountOmemoPreKeysParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
}

func (q *Queries) CountOmemoPreKeys(ctx context.Context, arg CountOmemoPreKeysParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOmemoPreKeys, arg.AccountJid, arg.Protocol)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOmemoDevices = `-- name: DeleteOmemoDevices :exec
DELETE FROM omemoDevice
WHERE accountJID = ?1 AND protocol = ?2 AND peerJID = ?3
`

type DeleteOmemoDevicesParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
	PeerJid    string `db:"peer_jid"`
}

func (q *Queries) DeleteOmemoDevices(ctx context.Context, arg DeleteOmemoDevicesParams) error {
	_, err := q.db.ExecContext(ctx, deleteOmemoDevices, arg.AccountJid, arg.Protocol, arg.PeerJid)
	return err
}

const deleteOmemoSession = `-- name: DeleteOmemoSession :exec
DELETE FROM omemoSession
WHERE accountJID = ?1 AND protocol = ?2 AND peerJID = ?3 AND deviceID = ?4
`

type DeleteOmemoSessionParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
	PeerJid    string `db:"peer_jid"`
	DeviceID   int64  `db:"device_id"`
}

func (q *Queries) DeleteOmemoSession(ctx context.Context, arg DeleteOmemoSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteOmemoSession,
		arg.AccountJid,
		arg.Protocol,
		arg.PeerJid,
		arg.DeviceID,
	)
	return err
}

const deleteOmemoStaleSignedPreKey = `-- name: DeleteOmemoStaleSignedPreKey :exec
DELETE FROM omemoSignedPreKey
WHERE accountJID = ?1 AND protocol = ?2 AND stale = TRUE
`

type DeleteOmemoStaleSignedPreKeyParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
}

func (q *Queries) DeleteOmemoStaleSignedPreKey(ctx context.Context, arg DeleteOmemoStaleSignedPreKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteOmemoStaleSignedPreKey, arg.AccountJid, arg.Protocol)
	return err
}

const deleteReactionsByReactor = `-- name: DeleteReactionsByReactor :exec
DELETE FROM messageReactions
WHERE accountJID = ?1
	AND rosterJID = ?2
	AND idAttr = ?3
	AND fromJID = ?4
`

type DeleteReactionsByReactorParams struct {
	AccountJid string `db:"account_jid"`
	RosterJid  string `db:"roster_jid"`
	IDAttr     string `db:"id_attr"`
	FromJid    string `db:"from_jid"`
}

func (q *Queries) DeleteReactionsByReactor(ctx context.Context, arg DeleteReactionsByReactorParams) error {
	_, err := q.db.ExecContext(ctx, deleteReactionsByReactor,
		arg.AccountJid,
		arg.RosterJid,
		arg.IDAttr,
		arg.FromJid,
	)
	return err
}

const deleteRosterByJID = `-- name: DeleteRosterByJID :exec
DELETE FROM rosterJIDs
WHERE accountJID = ?1
	AND jid = ?2
`

type DeleteRosterByJIDParams struct {
	AccountJid string `db:"account_jid"`
	Jid        string `db:"jid"`
}

func (q *Queries) DeleteRosterByJID(ctx context.Context, arg DeleteRosterByJIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteRosterByJID, arg.AccountJid, arg.Jid)
	return err
}

const getCapsByJID = `-- name: GetCapsByJID :one
SELECT
	hash,
	ver
FROM entityCaps AS c
INNER JOIN discoJID AS j
	ON j.caps = c.id
WHERE j.jid = ?
`

type GetCapsByJIDRow struct {
	Hash string `db:"hash"`
	Ver  string `db:"ver"`
}

func (q *Queries) GetCapsByJID(ctx context.Context, jid string) (GetCapsByJIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCapsByJID, jid)
	var i GetCapsByJIDRow
	err := row.Scan(&i.Hash, &i.Ver)
	return i, err
}

const getChatEncryptionMode = `-- name: GetChatEncryptionMode :one
SELECT mode
FROM chatEncryption
WHERE accountJID = ?1
	AND rosterJID = ?2
`

type GetChatEncryptionModeParams struct {
	AccountJid string `db:"account_jid"`
	RosterJid  string `db:"roster_jid"`
}

func (q *Queries) GetChatEncryptionMode(ctx context.Context, arg GetChatEncryptionModeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getChatEncryptionMode, arg.AccountJid, arg.RosterJid)
	var mode string
	err := row.Scan(&mode)
	return mode, err
}

const getDiscoFeaturesByJID = `-- name: GetDiscoFeaturesByJID :many
SELECT
	var
FROM discoFeatures AS f
INNER JOIN discoFeatureJID AS fj
	ON fj.feat = f.id
INNER JOIN discoJID AS j
	ON j.id = fj.jid
WHERE j.jid = ?
`

func (q *Queries) GetDiscoFeaturesByJID(ctx context.Context, jid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDiscoFeaturesByJID, jid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var var_ string
		if err := rows.Scan(&var_); err != nil {
			return nil, err
		}
		items = append(items, var_)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscoFormsByJID = `-- name: GetDiscoFormsByJID :one
SELECT forms
FROM discoJID AS j
WHERE j.jid = ?
`

func (q *Queries) GetDiscoFormsByJID(ctx context.Context, jid string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getDiscoFormsByJID, jid)
	var forms sql.NullString
	err := row.Scan(&forms)
	return forms, err
}

const getDiscoIdentitiesByJID = `-- name: GetDiscoIdentitiesByJID :many
SELECT
	cat,
	name,
	typ,
	lang
FROM discoIdentity AS i
INNER JOIN discoIdentityJID AS ij
	ON ij.ident = i.id
INNER JOIN discoJID AS j
	ON j.id = ij.jid
WHERE j.jid = ?
`

type GetDiscoIdentitiesByJIDRow struct {
	Cat  string `db:"cat"`
	Name string `db:"name"`
	Typ  string `db:"typ"`
	Lang string `db:"lang"`
}

func (q *Queries) GetDiscoIdentitiesByJID(ctx context.Context, jid string) ([]GetDiscoIdentitiesByJIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getDiscoIdentitiesByJID, jid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDiscoIdentitiesByJIDRow
	for rows.Next() {
		var i GetDiscoIdentitiesByJIDRow
		if err := rows.Scan(
			&i.Cat,
			&i.Name,
			&i.Typ,
			&i.Lang,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocalKeySalt = `-- name: GetLocalKeySalt :one
SELECT salt
FROM localKeySalt
WHERE id = 0
`

func (q *Queries) GetLocalKeySalt(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getLocalKeySalt)
	var salt []byte
	err := row.Scan(&salt)
	return salt, err
}

const getOmemoCurrentSignedPreKey = `-- name: GetOmemoCurrentSignedPreKey :one
SELECT id, public, private, signature
FROM omemoSignedPreKey
WHERE accountJID = ?1 AND protocol = ?2 AND stale = FALSE
ORDER BY id DESC
LIMIT 1
`

type GetOmemoCurrentSignedPreKeyParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
}

type GetOmemoCurrentSignedPreKeyRow struct {
	ID        int64  `db:"id"`
	Public    []byte `db:"public"`
	Private   []byte `db:"private"`
	Signature []byte `db:"signature"`
}

func (q *Queries) GetOmemoCurrentSignedPreKey(ctx context.Context, arg GetOmemoCurrentSignedPreKeyParams) (GetOmemoCurrentSignedPreKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getOmemoCurrentSignedPreKey, arg.AccountJid, arg.Protocol)
	var i GetOmemoCurrentSignedPreKeyRow
	err := row.Scan(
		&i.ID,
		&i.Public,
		&i.Private,
		&i.Signature,
	)
	return i, err
}

const getOmemoIdentity = `-- name: GetOmemoIdentity :one
SELECT privateKey, deviceID
FROM omemoIdentity
WHERE accountJID = ?1 AND protocol = ?2
`

type GetOmemoIdentityParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
}

type GetOmemoIdentityRow struct {
	Privatekey []byte `db:"privatekey"`
	Deviceid   int64  `db:"deviceid"`
}

func (q *Queries) GetOmemoIdentity(ctx context.Context, arg GetOmemoIdentityParams) (GetOmemoIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getOmemoIdentity, arg.AccountJid, arg.Protocol)
	var i GetOmemoIdentityRow
	err := row.Scan(&i.Privatekey, &i.Deviceid)
	return i, err
}

const getOmemoNextPreKeyID = `-- name: GetOmemoNextPreKeyID :one
SELECT nextID
FROM omemoNextPreKeyID
WHERE accountJID = ?1 AND protocol = ?2
`

type GetOmemoNextPreKeyIDParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
}

func (q *Queries) GetOmemoNextPreKeyID(ctx context.Context, arg GetOmemoNextPreKeyIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOmemoNextPreKeyID, arg.AccountJid, arg.Protocol)
	var nextid int64
	err := row.Scan(&nextid)
	return nextid, err
}

const getOmemoPeerProtocol = `-- name: GetOmemoPeerProtocol :one
SELECT protocol, probedAt
FROM omemoPeerProtocol
WHERE accountJID = ?1 AND peerJID = ?2
`

type GetOmemoPeerProtocolParams struct {
	AccountJid string `db:"account_jid"`
	PeerJid    string `db:"peer_jid"`
}

type GetOmemoPeerProtocolRow struct {
	Protocol string `db:"protocol"`
	Probedat int64  `db:"probedat"`
}

func (q *Queries) GetOmemoPeerProtocol(ctx context.Context, arg GetOmemoPeerProtocolParams) (GetOmemoPeerProtocolRow, error) {
	row := q.db.QueryRowContext(ctx, getOmemoPeerProtocol, arg.AccountJid, arg.PeerJid)
	var i GetOmemoPeerProtocolRow
	err := row.Scan(&i.Protocol, &i.Probedat)
	return i, err
}

const getOmemoRemoteIdentity = `-- name: GetOmemoRemoteIdentity :one
SELECT identityKey
FROM omemoRemoteIdentity
WHERE accountJID = ?1 AND protocol = ?2 AND peerJID = ?3 AND deviceID = ?4
`

type GetOmemoRemoteIdentityParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
	PeerJid    string `db:"peer_jid"`
	DeviceID   int64  `db:"device_id"`
}

func (q *Queries) GetOmemoRemoteIdentity(ctx context.Context, arg GetOmemoRemoteIdentityParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getOmemoRemoteIdentity,
		arg.AccountJid,
		arg.Protocol,
		arg.PeerJid,
		arg.DeviceID,
	)
	var identitykey []byte
	err := row.Scan(&identitykey)
	return identitykey, err
}

const getOmemoSession = `-- name: GetOmemoSession :one
SELECT data
FROM omemoSession
WHERE accountJID = ?1 AND protocol = ?2 AND peerJID = ?3 AND deviceID = ?4
`

type GetOmemoSessionParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
	PeerJid    string `db:"peer_jid"`
	DeviceID   int64  `db:"device_id"`
}

func (q *Queries) GetOmemoSession(ctx context.Context, arg GetOmemoSessionParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getOmemoSession,
		arg.AccountJid,
		arg.Protocol,
		arg.PeerJid,
		arg.DeviceID,
	)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getOmemoStaleSignedPreKey = `-- name: GetOmemoStaleSignedPreKey :one
SELECT id, public, private, signature
FROM omemoSignedPreKey
WHERE accountJID = ?1 AND protocol = ?2 AND stale = TRUE
LIMIT 1
`

type GetOmemoStaleSignedPreKeyParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
}

type GetOmemoStaleSignedPreKeyRow struct {
	ID        int64  `db:"id"`
	Public    []byte `db:"public"`
	Private   []byte `db:"private"`
	Signature []byte `db:"signature"`
}

func (q *Queries) GetOmemoStaleSignedPreKey(ctx context.Context, arg GetOmemoStaleSignedPreKeyParams) (GetOmemoStaleSignedPreKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getOmemoStaleSignedPreKey, arg.AccountJid, arg.Protocol)
	var i GetOmemoStaleSignedPreKeyRow
	err := row.Scan(
		&i.ID,
		&i.Public,
		&i.Private,
		&i.Signature,
	)
	return i, err
}

const getOmemoTrust = `-- name: GetOmemoTrust :one
SELECT state
FROM omemoTrust
WHERE accountJID = ?1 AND protocol = ?2 AND identityKey = ?3
`

type GetOmemoTrustParams struct {
	AccountJid  string `db:"account_jid"`
	Protocol    string `db:"protocol"`
	IdentityKey []byte `db:"identity_key"`
}

func (q *Queries) GetOmemoTrust(ctx context.Context, arg GetOmemoTrustParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOmemoTrust, arg.AccountJid, arg.Protocol, arg.IdentityKey)
	var state int64
	err := row.Scan(&state)
	return state, err
}

const getPGPPeerKey = `-- name: GetPGPPeerKey :one
SELECT fingerprint
FROM pgpPeerKeys
WHERE accountJID = ?1
	AND jid = ?2
`

type GetPGPPeerKeyParams struct {
	AccountJid string `db:"account_jid"`
	Jid        string `db:"jid"`
}

func (q *Queries) GetPGPPeerKey(ctx context.Context, arg GetPGPPeerKeyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPGPPeerKey, arg.AccountJid, arg.Jid)
	var fingerprint string
	err := row.Scan(&fingerprint)
	return fingerprint, err
}

const getRosterVersion = `-- name: GetRosterVersion :one
SELECT ver
FROM rosterVer
WHERE accountJID = ?1
`

func (q *Queries) GetRosterVersion(ctx context.Context, accountJid string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRosterVersion, accountJid)
	var ver string
	err := row.Scan(&ver)
	return ver, err
}

const getServicesByFeature = `-- name: GetServicesByFeature :many
SELECT j.jid
FROM discoJID AS j
INNER JOIN discoFeatureJID AS fj
	ON fj.jid = j.id
INNER JOIN discoFeatures AS f
	ON fj.feat = f.id
WHERE f.var = ?
`

func (q *Queries) GetServicesByFeature(ctx context.Context, var_ string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getServicesByFeature, var_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var jid string
		if err := rows.Scan(&jid); err != nil {
			return nil, err
		}
		items = append(items, jid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasGPGChat = `-- name: HasGPGChat :one
SELECT EXISTS(
	SELECT 1 FROM chatEncryption
	WHERE accountJID = ?1 AND mode = 'gpg'
)
`

func (q *Queries) HasGPGChat(ctx context.Context, accountJid string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasGPGChat, accountJid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const incrementChatUnread = `-- name: IncrementChatUnread :exec
INSERT INTO chatUnread (accountJID, rosterJID, count)
VALUES (?1, ?2, ?3)
ON CONFLICT (accountJID, rosterJID) DO UPDATE
SET count = count + excluded.count
`

type IncrementChatUnreadParams struct {
	AccountJid string `db:"account_jid"`
	RosterJid  string `db:"roster_jid"`
	Delta      int64  `db:"delta"`
}

func (q *Queries) IncrementChatUnread(ctx context.Context, arg IncrementChatUnreadParams) error {
	_, err := q.db.ExecContext(ctx, incrementChatUnread, arg.AccountJid, arg.RosterJid, arg.Delta)
	return err
}

const insertDiscoFeatureJID = `-- name: InsertDiscoFeatureJID :exec
INSERT INTO discoFeatureJID (jid, feat)
VALUES (?, ?)
ON CONFLICT(jid, feat) DO NOTHING
`

type InsertDiscoFeatureJIDParams struct {
	Jid  int64 `db:"jid"`
	Feat int64 `db:"feat"`
}

func (q *Queries) InsertDiscoFeatureJID(ctx context.Context, arg InsertDiscoFeatureJIDParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoFeatureJID, arg.Jid, arg.Feat)
	return err
}

const insertDiscoIdentityJID = `-- name: InsertDiscoIdentityJID :exec
INSERT INTO discoIdentityJID (jid, ident)
VALUES (?, ?)
ON CONFLICT (jid, ident) DO NOTHING
`

type InsertDiscoIdentityJIDParams struct {
	Jid   int64 `db:"jid"`
	Ident int64 `db:"ident"`
}

func (q *Queries) InsertDiscoIdentityJID(ctx context.Context, arg InsertDiscoIdentityJIDParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoIdentityJID, arg.Jid, arg.Ident)
	return err
}

const insertEntityCaps = `-- name: InsertEntityCaps :exec
INSERT INTO entityCaps (hash, ver)
VALUES (?, ?)
ON CONFLICT (hash, ver) DO NOTHING
`

type InsertEntityCapsParams struct {
	Hash string `db:"hash"`
	Ver  string `db:"ver"`
}

func (q *Queries) InsertEntityCaps(ctx context.Context, arg InsertEntityCapsParams) error {
	_, err := q.db.ExecContext(ctx, insertEntityCaps, arg.Hash, arg.Ver)
	return err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (
	accountJID,
	sent,
	toAttr,
	fromAttr,
	idAttr,
	body,
	encrypted,
	e2eEncrypted,
	e2eeMethod,
	stanzaType,
	originID,
	delay,
	rosterJID,
	archiveID,
	replyToIdAttr,
	oobURLs
)
VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	?8,
	?9,
	?10,
	?11,
	IFNULL(
		NULLIF(?12, 0),
		CAST(strftime('%s', 'now') AS INTEGER)
	),
	?13,
	?14,
	?15,
	?16
)
ON CONFLICT (accountJID, originID, fromAttr) DO UPDATE
SET archiveID = excluded.archiveID
RETURNING id
`

type InsertMessageParams struct {
	AccountJid    string         `db:"account_jid"`
	Sent          bool           `db:"sent"`
	ToAttr        sql.NullString `db:"to_attr"`
	FromAttr      sql.NullString `db:"from_attr"`
	IDAttr        sql.NullString `db:"id_attr"`
	Body          sql.NullString `db:"body"`
	Encrypted     bool           `db:"encrypted"`
	E2eEncrypted  bool           `db:"e2e_encrypted"`
	E2eeMethod    sql.NullString `db:"e2ee_method"`
	StanzaType    string         `db:"stanza_type"`
	OriginID      sql.NullString `db:"origin_id"`
	Delay         interface{}    `db:"delay"`
	RosterJid     sql.NullString `db:"roster_jid"`
	ArchiveID     sql.NullString `db:"archive_id"`
	ReplyToIDAttr sql.NullString `db:"reply_to_id_attr"`
	OobUrls       sql.NullString `db:"oob_urls"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.AccountJid,
		arg.Sent,
		arg.ToAttr,
		arg.FromAttr,
		arg.IDAttr,
		arg.Body,
		arg.Encrypted,
		arg.E2eEncrypted,
		arg.E2eeMethod,
		arg.StanzaType,
		arg.OriginID,
		arg.Delay,
		arg.RosterJid,
		arg.ArchiveID,
		arg.ReplyToIDAttr,
		arg.OobUrls,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertOmemoDevice = `-- name: InsertOmemoDevice :exec
INSERT INTO omemoDevice (accountJID, protocol, peerJID, deviceID)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (accountJID, protocol, peerJID, deviceID) DO NOTHING
`

type InsertOmemoDeviceParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
	PeerJid    string `db:"peer_jid"`
	DeviceID   int64  `db:"device_id"`
}

func (q *Queries) InsertOmemoDevice(ctx context.Context, arg InsertOmemoDeviceParams) error {
	_, err := q.db.ExecContext(ctx, insertOmemoDevice,
		arg.AccountJid,
		arg.Protocol,
		arg.PeerJid,
		arg.DeviceID,
	)
	return err
}

const insertOmemoPreKey = `-- name: InsertOmemoPreKey :exec
INSERT INTO omemoPreKey (accountJID, protocol, id, public, private)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertOmemoPreKeyParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
	ID         int64  `db:"id"`
	Public     []byte `db:"public"`
	Private    []byte `db:"private"`
}

func (q *Queries) InsertOmemoPreKey(ctx context.Context, arg InsertOmemoPreKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertOmemoPreKey,
		arg.AccountJid,
		arg.Protocol,
		arg.ID,
		arg.Public,
		arg.Private,
	)
	return err
}

const insertOmemoSignedPreKey = `-- name: InsertOmemoSignedPreKey :exec
INSERT INTO omemoSignedPreKey (accountJID, protocol, id, public, private, signature, stale)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, FALSE)
`

type InsertOmemoSignedPreKeyParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
	ID         int64  `db:"id"`
	Public     []byte `db:"public"`
	Private    []byte `db:"private"`
	Signature  []byte `db:"signature"`
}

func (q *Queries) InsertOmemoSignedPreKey(ctx context.Context, arg InsertOmemoSignedPreKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertOmemoSignedPreKey,
		arg.AccountJid,
		arg.Protocol,
		arg.ID,
		arg.Public,
		arg.Private,
		arg.Signature,
	)
	return err
}

const insertReaction = `-- name: InsertReaction :exec
INSERT INTO messageReactions (accountJID, rosterJID, idAttr, fromJID, emoji)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (accountJID, rosterJID, idAttr, fromJID, emoji) DO NOTHING
`

type InsertReactionParams struct {
	AccountJid string `db:"account_jid"`
	RosterJid  string `db:"roster_jid"`
	IDAttr     string `db:"id_attr"`
	FromJid    string `db:"from_jid"`
	Emoji      string `db:"emoji"`
}

func (q *Queries) InsertReaction(ctx context.Context, arg InsertReactionParams) error {
	_, err := q.db.ExecContext(ctx, insertReaction,
		arg.AccountJid,
		arg.RosterJid,
		arg.IDAttr,
		arg.FromJid,
		arg.Emoji,
	)
	return err
}

const insertRosterGroup = `-- name: InsertRosterGroup :exec
INSERT INTO rosterGroups (accountJID, jid, name)
VALUES (?1, ?2, ?3)
ON CONFLICT DO NOTHING
`

type InsertRosterGroupParams struct {
	AccountJid string `db:"account_jid"`
	Jid        string `db:"jid"`
	Name       string `db:"name"`
}

func (q *Queries) InsertRosterGroup(ctx context.Context, arg InsertRosterGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertRosterGroup, arg.AccountJid, arg.Jid, arg.Name)
	return err
}

const listAllMessages = `-- name: ListAllMessages :many
SELECT
	accountJID,
	sent,
	toAttr,
	fromAttr,
	idAttr,
	body,
	encrypted,
	e2eEncrypted,
	e2eeMethod,
	originID,
	stanzaType,
	received,
	delay,
	rosterJID,
	archiveID,
	replyToIdAttr,
	retracted,
	edited,
	delivered,
	oobURLs
FROM messages
ORDER BY delay ASC, id ASC
`

type ListAllMessagesRow struct {
	Accountjid    string         `db:"accountjid"`
	Sent          bool           `db:"sent"`
	Toattr        sql.NullString `db:"toattr"`
	Fromattr      sql.NullString `db:"fromattr"`
	Idattr        sql.NullString `db:"idattr"`
	Body          sql.NullString `db:"body"`
	Encrypted     bool           `db:"encrypted"`
	E2eencrypted  bool           `db:"e2eencrypted"`
	E2eemethod    sql.NullString `db:"e2eemethod"`
	Originid      sql.NullString `db:"originid"`
	Stanzatype    string         `db:"stanzatype"`
	Received      bool           `db:"received"`
	Delay         int64          `db:"delay"`
	Rosterjid     sql.NullString `db:"rosterjid"`
	Archiveid     sql.NullString `db:"archiveid"`
	Replytoidattr sql.NullString `db:"replytoidattr"`
	Retracted     bool           `db:"retracted"`
	Edited        bool           `db:"edited"`
	Delivered     bool           `db:"delivered"`
	Ooburls       sql.NullString `db:"ooburls"`
}

// Every message row across every account, oldest first, used by the
// "export" CLI command. Bodies come back exactly as stored (plaintext or
// localstore-sealed); the caller decrypts.
func (q *Queries) ListAllMessages(ctx context.Context) ([]ListAllMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllMessagesRow
	for rows.Next() {
		var i ListAllMessagesRow
		if err := rows.Scan(
			&i.Accountjid,
			&i.Sent,
			&i.Toattr,
			&i.Fromattr,
			&i.Idattr,
			&i.Body,
			&i.Encrypted,
			&i.E2eencrypted,
			&i.E2eemethod,
			&i.Originid,
			&i.Stanzatype,
			&i.Received,
			&i.Delay,
			&i.Rosterjid,
			&i.Archiveid,
			&i.Replytoidattr,
			&i.Retracted,
			&i.Edited,
			&i.Delivered,
			&i.Ooburls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllReactions = `-- name: ListAllReactions :many
SELECT accountJID, rosterJID, idAttr, fromJID, emoji
FROM messageReactions
`

type ListAllReactionsRow struct {
	Accountjid string `db:"accountjid"`
	Rosterjid  string `db:"rosterjid"`
	Idattr     string `db:"idattr"`
	Fromjid    string `db:"fromjid"`
	Emoji      string `db:"emoji"`
}

// Every reaction row across every account, used by the "export" CLI
// command alongside ListAllMessages.
func (q *Queries) ListAllReactions(ctx context.Context) ([]ListAllReactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllReactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReactionsRow
	for rows.Next() {
		var i ListAllReactionsRow
		if err := rows.Scan(
			&i.Accountjid,
			&i.Rosterjid,
			&i.Idattr,
			&i.Fromjid,
			&i.Emoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatUnread = `-- name: ListChatUnread :many
SELECT rosterJID, count
FROM chatUnread
WHERE accountJID = ?1 AND count > 0
`

type ListChatUnreadRow struct {
	Rosterjid string `db:"rosterjid"`
	Count     int64  `db:"count"`
}

func (q *Queries) ListChatUnread(ctx context.Context, accountJid string) ([]ListChatUnreadRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatUnread, accountJid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatUnreadRow
	for rows.Next() {
		var i ListChatUnreadRow
		if err := rows.Scan(&i.Rosterjid, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestArchiveIDs = `-- name: ListLatestArchiveIDs :many
SELECT
	m.rosterJID,
	m.archiveID,
	MAX(m.delay)
FROM messages AS m
WHERE m.accountJID = ?1
	AND m.archiveID IS NOT NULL
GROUP BY m.rosterJID
`

type ListLatestArchiveIDsRow struct {
	Rosterjid sql.NullString `db:"rosterjid"`
	Archiveid sql.NullString `db:"archiveid"`
	Max       interface{}    `db:"max"`
}

func (q *Queries) ListLatestArchiveIDs(ctx context.Context, accountJid string) ([]ListLatestArchiveIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestArchiveIDs, accountJid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestArchiveIDsRow
	for rows.Next() {
		var i ListLatestArchiveIDsRow
		if err := rows.Scan(&i.Rosterjid, &i.Archiveid, &i.Max); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByRoster = `-- name: ListMessagesByRoster :many
SELECT
	sent,
	toAttr,
	fromAttr,
	idAttr,
	body,
	encrypted,
	e2eEncrypted,
	e2eeMethod,
	stanzaType,
	delay,
	replyToIdAttr,
	retracted,
	edited,
	delivered,
	oobURLs
FROM messages
WHERE accountJID = ?1
	AND rosterJID = ?2
	AND stanzaType = COALESCE(
		NULLIF(?3, ''),
		stanzaType
	)
ORDER BY delay ASC
`

type ListMessagesByRosterParams struct {
	AccountJid string         `db:"account_jid"`
	RosterJid  sql.NullString `db:"roster_jid"`
	StanzaType interface{}    `db:"stanza_type"`
}

type ListMessagesByRosterRow struct {
	Sent          bool           `db:"sent"`
	Toattr        sql.NullString `db:"toattr"`
	Fromattr      sql.NullString `db:"fromattr"`
	Idattr        sql.NullString `db:"idattr"`
	Body          sql.NullString `db:"body"`
	Encrypted     bool           `db:"encrypted"`
	E2eencrypted  bool           `db:"e2eencrypted"`
	E2eemethod    sql.NullString `db:"e2eemethod"`
	Stanzatype    string         `db:"stanzatype"`
	Delay         int64          `db:"delay"`
	Replytoidattr sql.NullString `db:"replytoidattr"`
	Retracted     bool           `db:"retracted"`
	Edited        bool           `db:"edited"`
	Delivered     bool           `db:"delivered"`
	Ooburls       sql.NullString `db:"ooburls"`
}

func (q *Queries) ListMessagesByRoster(ctx context.Context, arg ListMessagesByRosterParams) ([]ListMessagesByRosterRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByRoster, arg.AccountJid, arg.RosterJid, arg.StanzaType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByRosterRow
	for rows.Next() {
		var i ListMessagesByRosterRow
		if err := rows.Scan(
			&i.Sent,
			&i.Toattr,
			&i.Fromattr,
			&i.Idattr,
			&i.Body,
			&i.Encrypted,
			&i.E2eencrypted,
			&i.E2eemethod,
			&i.Stanzatype,
			&i.Delay,
			&i.Replytoidattr,
			&i.Retracted,
			&i.Edited,
			&i.Delivered,
			&i.Ooburls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByRosterBefore = `-- name: ListMessagesByRosterBefore :many
SELECT
	id,
	sent,
	toAttr,
	fromAttr,
	idAttr,
	body,
	encrypted,
	e2eEncrypted,
	e2eeMethod,
	stanzaType,
	delay,
	replyToIdAttr,
	retracted,
	edited,
	delivered,
	oobURLs
FROM messages
WHERE accountJID = ?1
	AND rosterJID = ?2
	AND stanzaType = COALESCE(
		NULLIF(?3, ''),
		stanzaType
	)
	AND (
		delay < ?4
		OR (delay = ?4 AND id < ?5)
	)
ORDER BY delay DESC, id DESC
LIMIT ?6
`

type ListMessagesByRosterBeforeParams struct {
	AccountJid  string         `db:"account_jid"`
	RosterJid   sql.NullString `db:"roster_jid"`
	StanzaType  interface{}    `db:"stanza_type"`
	BeforeDelay int64          `db:"before_delay"`
	BeforeID    int64          `db:"before_id"`
	PageLimit   int64          `db:"page_limit"`
}

type ListMessagesByRosterBeforeRow struct {
	ID            int64          `db:"id"`
	Sent          bool           `db:"sent"`
	Toattr        sql.NullString `db:"toattr"`
	Fromattr      sql.NullString `db:"fromattr"`
	Idattr        sql.NullString `db:"idattr"`
	Body          sql.NullString `db:"body"`
	Encrypted     bool           `db:"encrypted"`
	E2eencrypted  bool           `db:"e2eencrypted"`
	E2eemethod    sql.NullString `db:"e2eemethod"`
	Stanzatype    string         `db:"stanzatype"`
	Delay         int64          `db:"delay"`
	Replytoidattr sql.NullString `db:"replytoidattr"`
	Retracted     bool           `db:"retracted"`
	Edited        bool           `db:"edited"`
	Delivered     bool           `db:"delivered"`
	Ooburls       sql.NullString `db:"ooburls"`
}

// ListMessagesByRosterBefore returns one page of a chat's history older
// than the (before_delay, before_id) cursor, newest-first (the caller
// reverses rows back to chronological order for display). Pass
// math.MaxInt64 for both cursor args to fetch the most recent page. Keyset
// (not OFFSET) pagination: every page is an indexed range scan regardless
// of how deep the user has scrolled, and pages stay correct even as new
// messages are inserted concurrently. id (the table's rowid) breaks ties
// between messages sharing the same delay (second-granularity timestamp).
// Used instead of ListMessagesByRoster to avoid loading/decrypting an
// entire multi-thousand message history at once.
func (q *Queries) ListMessagesByRosterBefore(ctx context.Context, arg ListMessagesByRosterBeforeParams) ([]ListMessagesByRosterBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByRosterBefore,
		arg.AccountJid,
		arg.RosterJid,
		arg.StanzaType,
		arg.BeforeDelay,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByRosterBeforeRow
	for rows.Next() {
		var i ListMessagesByRosterBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.Sent,
			&i.Toattr,
			&i.Fromattr,
			&i.Idattr,
			&i.Body,
			&i.Encrypted,
			&i.E2eencrypted,
			&i.E2eemethod,
			&i.Stanzatype,
			&i.Delay,
			&i.Replytoidattr,
			&i.Retracted,
			&i.Edited,
			&i.Delivered,
			&i.Ooburls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOmemoDevices = `-- name: ListOmemoDevices :many
SELECT deviceID
FROM omemoDevice
WHERE accountJID = ?1 AND protocol = ?2 AND peerJID = ?3
`

type ListOmemoDevicesParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
	PeerJid    string `db:"peer_jid"`
}

func (q *Queries) ListOmemoDevices(ctx context.Context, arg ListOmemoDevicesParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listOmemoDevices, arg.AccountJid, arg.Protocol, arg.PeerJid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var deviceid int64
		if err := rows.Scan(&deviceid); err != nil {
			return nil, err
		}
		items = append(items, deviceid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOmemoPreKeys = `-- name: ListOmemoPreKeys :many
SELECT id, public, private
FROM omemoPreKey
WHERE accountJID = ?1 AND protocol = ?2
`

type ListOmemoPreKeysParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
}

type ListOmemoPreKeysRow struct {
	ID      int64  `db:"id"`
	Public  []byte `db:"public"`
	Private []byte `db:"private"`
}

func (q *Queries) ListOmemoPreKeys(ctx context.Context, arg ListOmemoPreKeysParams) ([]ListOmemoPreKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listOmemoPreKeys, arg.AccountJid, arg.Protocol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOmemoPreKeysRow
	for rows.Next() {
		var i ListOmemoPreKeysRow
		if err := rows.Scan(&i.ID, &i.Public, &i.Private); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsForMessage = `-- name: ListReactionsForMessage :many
SELECT fromJID, emoji
FROM messageReactions
WHERE accountJID = ?1
	AND rosterJID = ?2
	AND idAttr = ?3
`

type ListReactionsForMessageParams struct {
	AccountJid string `db:"account_jid"`
	RosterJid  string `db:"roster_jid"`
	IDAttr     string `db:"id_attr"`
}

type ListReactionsForMessageRow struct {
	Fromjid string `db:"fromjid"`
	Emoji   string `db:"emoji"`
}

func (q *Queries) ListReactionsForMessage(ctx context.Context, arg ListReactionsForMessageParams) ([]ListReactionsForMessageRow, error) {
	rows, err := q.db.QueryContext(ctx, listReactionsForMessage, arg.AccountJid, arg.RosterJid, arg.IDAttr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReactionsForMessageRow
	for rows.Next() {
		var i ListReactionsForMessageRow
		if err := rows.Scan(&i.Fromjid, &i.Emoji); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoster = `-- name: ListRoster :many
SELECT
	jid,
	name,
	subs
FROM rosterJIDs
WHERE accountJID = ?1
`

type ListRosterRow struct {
	Jid  string `db:"jid"`
	Name string `db:"name"`
	Subs string `db:"subs"`
}

func (q *Queries) ListRoster(ctx context.Context, accountJid string) ([]ListRosterRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoster, accountJid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRosterRow
	for rows.Next() {
		var i ListRosterRow
		if err := rows.Scan(&i.Jid, &i.Name, &i.Subs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageDelivered = `-- name: MarkMessageDelivered :execrows
UPDATE messages
SET delivered = TRUE
WHERE accountJID = ?1
	AND idAttr = ?2
	AND rosterJID = ?3
`

type MarkMessageDeliveredParams struct {
	AccountJid string         `db:"account_jid"`
	IDAttr     sql.NullString `db:"id_attr"`
	RosterJid  sql.NullString `db:"roster_jid"`
}

func (q *Queries) MarkMessageDelivered(ctx context.Context, arg MarkMessageDeliveredParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMessageDelivered, arg.AccountJid, arg.IDAttr, arg.RosterJid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMessageEdited = `-- name: MarkMessageEdited :execrows
UPDATE messages
SET edited = TRUE
WHERE accountJID = ?1
	AND idAttr = ?2
	AND rosterJID = ?3
`

type MarkMessageEditedParams struct {
	AccountJid string         `db:"account_jid"`
	IDAttr     sql.NullString `db:"id_attr"`
	RosterJid  sql.NullString `db:"roster_jid"`
}

func (q *Queries) MarkMessageEdited(ctx context.Context, arg MarkMessageEditedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMessageEdited, arg.AccountJid, arg.IDAttr, arg.RosterJid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMessageRetracted = `-- name: MarkMessageRetracted :execrows
UPDATE messages
SET retracted = TRUE
WHERE accountJID = ?1
	AND idAttr = ?2
	AND rosterJID = ?3
`

type MarkMessageRetractedParams struct {
	AccountJid string         `db:"account_jid"`
	IDAttr     sql.NullString `db:"id_attr"`
	RosterJid  sql.NullString `db:"roster_jid"`
}

func (q *Queries) MarkMessageRetracted(ctx context.Context, arg MarkMessageRetractedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMessageRetracted, arg.AccountJid, arg.IDAttr, arg.RosterJid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMessagesReceived = `-- name: MarkMessagesReceived :exec
UPDATE messages
SET received = TRUE
WHERE accountJID = ?1
	AND sent = TRUE
	AND (
		idAttr = ?2
		OR originID = ?2
	)
`

type MarkMessagesReceivedParams struct {
	AccountJid string         `db:"account_jid"`
	MessageID  sql.NullString `db:"message_id"`
}

func (q *Queries) MarkMessagesReceived(ctx context.Context, arg MarkMessagesReceivedParams) error {
	_, err := q.db.ExecContext(ctx, markMessagesReceived, arg.AccountJid, arg.MessageID)
	return err
}

const markOmemoSignedPreKeyStale = `-- name: MarkOmemoSignedPreKeyStale :exec
UPDATE omemoSignedPreKey
SET stale = TRUE
WHERE accountJID = ?1 AND protocol = ?2 AND stale = FALSE
`

type MarkOmemoSignedPreKeyStaleParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
}

func (q *Queries) MarkOmemoSignedPreKeyStale(ctx context.Context, arg MarkOmemoSignedPreKeyStaleParams) error {
	_, err := q.db.ExecContext(ctx, markOmemoSignedPreKeyStale, arg.AccountJid, arg.Protocol)
	return err
}

const messageExistsByArchiveID = `-- name: MessageExistsByArchiveID :one
SELECT EXISTS (
	SELECT 1 FROM messages
	WHERE accountJID = ?1
		AND archiveID = ?2
)
`

type MessageExistsByArchiveIDParams struct {
	AccountJid string         `db:"account_jid"`
	ArchiveID  sql.NullString `db:"archive_id"`
}

// Checked before decrypting a XEP-0313 (MAM) archive item, so a page
// re-fetched after a stale cursor doesn't re-run OMEMO decrypt (and its
// ratchet side effects) on ciphertext already stored.
func (q *Queries) MessageExistsByArchiveID(ctx context.Context, arg MessageExistsByArchiveIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, messageExistsByArchiveID, arg.AccountJid, arg.ArchiveID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const messageExistsByIDAttr = `-- name: MessageExistsByIDAttr :one
SELECT EXISTS (
	SELECT 1 FROM messages
	WHERE accountJID = ?1
		AND rosterJID = ?2
		AND idAttr = ?3
)
`

type MessageExistsByIDAttrParams struct {
	AccountJid string         `db:"account_jid"`
	RosterJid  sql.NullString `db:"roster_jid"`
	IDAttr     sql.NullString `db:"id_attr"`
}

// Checked before decrypting a live incoming OMEMO message, so a message
// already backfilled via MAM (or otherwise already stored) isn't decrypted
// a second time.
func (q *Queries) MessageExistsByIDAttr(ctx context.Context, arg MessageExistsByIDAttrParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, messageExistsByIDAttr, arg.AccountJid, arg.RosterJid, arg.IDAttr)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const putOmemoRemoteIdentity = `-- name: PutOmemoRemoteIdentity :exec
INSERT INTO omemoRemoteIdentity (accountJID, protocol, peerJID, deviceID, identityKey)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (accountJID, protocol, peerJID, deviceID) DO UPDATE
SET identityKey = excluded.identityKey
`

type PutOmemoRemoteIdentityParams struct {
	AccountJid  string `db:"account_jid"`
	Protocol    string `db:"protocol"`
	PeerJid     string `db:"peer_jid"`
	DeviceID    int64  `db:"device_id"`
	IdentityKey []byte `db:"identity_key"`
}

func (q *Queries) PutOmemoRemoteIdentity(ctx context.Context, arg PutOmemoRemoteIdentityParams) error {
	_, err := q.db.ExecContext(ctx, putOmemoRemoteIdentity,
		arg.AccountJid,
		arg.Protocol,
		arg.PeerJid,
		arg.DeviceID,
		arg.IdentityKey,
	)
	return err
}

const putOmemoSession = `-- name: PutOmemoSession :exec
INSERT INTO omemoSession (accountJID, protocol, peerJID, deviceID, data)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (accountJID, protocol, peerJID, deviceID) DO UPDATE
SET data = excluded.data
`

type PutOmemoSessionParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
	PeerJid    string `db:"peer_jid"`
	DeviceID   int64  `db:"device_id"`
	Data       []byte `db:"data"`
}

func (q *Queries) PutOmemoSession(ctx context.Context, arg PutOmemoSessionParams) error {
	_, err := q.db.ExecContext(ctx, putOmemoSession,
		arg.AccountJid,
		arg.Protocol,
		arg.PeerJid,
		arg.DeviceID,
		arg.Data,
	)
	return err
}

const resetChatUnread = `-- name: ResetChatUnread :exec
INSERT INTO chatUnread (accountJID, rosterJID, count)
VALUES (?1, ?2, 0)
ON CONFLICT (accountJID, rosterJID) DO UPDATE
SET count = 0
`

type ResetChatUnreadParams struct {
	AccountJid string `db:"account_jid"`
	RosterJid  string `db:"roster_jid"`
}

func (q *Queries) ResetChatUnread(ctx context.Context, arg ResetChatUnreadParams) error {
	_, err := q.db.ExecContext(ctx, resetChatUnread, arg.AccountJid, arg.RosterJid)
	return err
}

const setChatEncryptionMode = `-- name: SetChatEncryptionMode :exec
INSERT INTO chatEncryption (accountJID, rosterJID, mode)
VALUES (?1, ?2, ?3)
ON CONFLICT (accountJID, rosterJID) DO UPDATE
SET mode = excluded.mode
`

type SetChatEncryptionModeParams struct {
	AccountJid string `db:"account_jid"`
	RosterJid  string `db:"roster_jid"`
	Mode       string `db:"mode"`
}

func (q *Queries) SetChatEncryptionMode(ctx context.Context, arg SetChatEncryptionModeParams) error {
	_, err := q.db.ExecContext(ctx, setChatEncryptionMode, arg.AccountJid, arg.RosterJid, arg.Mode)
	return err
}

const setLocalKeySalt = `-- name: SetLocalKeySalt :exec
INSERT INTO localKeySalt (id, salt)
VALUES (FALSE, ?)
ON CONFLICT(id) DO UPDATE
SET salt = excluded.salt
`

func (q *Queries) SetLocalKeySalt(ctx context.Context, salt []byte) error {
	_, err := q.db.ExecContext(ctx, setLocalKeySalt, salt)
	return err
}

const setOmemoIdentity = `-- name: SetOmemoIdentity :exec
INSERT INTO omemoIdentity (accountJID, protocol, privateKey, deviceID)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (accountJID, protocol) DO UPDATE
SET privateKey = excluded.privateKey, deviceID = excluded.deviceID
`

type SetOmemoIdentityParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
	PrivateKey []byte `db:"private_key"`
	DeviceID   int64  `db:"device_id"`
}

func (q *Queries) SetOmemoIdentity(ctx context.Context, arg SetOmemoIdentityParams) error {
	_, err := q.db.ExecContext(ctx, setOmemoIdentity,
		arg.AccountJid,
		arg.Protocol,
		arg.PrivateKey,
		arg.DeviceID,
	)
	return err
}

const setOmemoNextPreKeyID = `-- name: SetOmemoNextPreKeyID :exec
INSERT INTO omemoNextPreKeyID (accountJID, protocol, nextID)
VALUES (?1, ?2, ?3)
ON CONFLICT (accountJID, protocol) DO UPDATE
SET nextID = excluded.nextID
`

type SetOmemoNextPreKeyIDParams struct {
	AccountJid string `db:"account_jid"`
	Protocol   string `db:"protocol"`
	NextID     int64  `db:"next_id"`
}

func (q *Queries) SetOmemoNextPreKeyID(ctx context.Context, arg SetOmemoNextPreKeyIDParams) error {
	_, err := q.db.ExecContext(ctx, setOmemoNextPreKeyID, arg.AccountJid, arg.Protocol, arg.NextID)
	return err
}

const setOmemoPeerProtocol = `-- name: SetOmemoPeerProtocol :exec
INSERT INTO omemoPeerProtocol (accountJID, peerJID, protocol, probedAt)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (accountJID, peerJID) DO UPDATE
SET protocol = excluded.protocol, probedAt = excluded.probedAt
`

type SetOmemoPeerProtocolParams struct {
	AccountJid string `db:"account_jid"`
	PeerJid    string `db:"peer_jid"`
	Protocol   string `db:"protocol"`
	ProbedAt   int64  `db:"probed_at"`
}

func (q *Queries) SetOmemoPeerProtocol(ctx context.Context, arg SetOmemoPeerProtocolParams) error {
	_, err := q.db.ExecContext(ctx, setOmemoPeerProtocol,
		arg.AccountJid,
		arg.PeerJid,
		arg.Protocol,
		arg.ProbedAt,
	)
	return err
}

const setOmemoTrust = `-- name: SetOmemoTrust :exec
INSERT INTO omemoTrust (accountJID, protocol, identityKey, state)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (accountJID, protocol, identityKey) DO UPDATE
SET state = excluded.state
`

type SetOmemoTrustParams struct {
	AccountJid  string `db:"account_jid"`
	Protocol    string `db:"protocol"`
	IdentityKey []byte `db:"identity_key"`
	State       int64  `db:"state"`
}

func (q *Queries) SetOmemoTrust(ctx context.Context, arg SetOmemoTrustParams) error {
	_, err := q.db.ExecContext(ctx, setOmemoTrust,
		arg.AccountJid,
		arg.Protocol,
		arg.IdentityKey,
		arg.State,
	)
	return err
}

const truncateRoster = `-- name: TruncateRoster :exec
DELETE FROM rosterJIDs
WHERE accountJID = ?1
`

func (q *Queries) TruncateRoster(ctx context.Context, accountJid string) error {
	_, err := q.db.ExecContext(ctx, truncateRoster, accountJid)
	return err
}

const updateMessageBodyByID = `-- name: UpdateMessageBodyByID :execrows
UPDATE messages
SET
	body = ?1,
	encrypted = ?2,
	e2eEncrypted = ?3,
	e2eeMethod = ?4,
	edited = ?5
WHERE accountJID = ?6
	AND idAttr = ?7
	AND rosterJID = ?8
`

type UpdateMessageBodyByIDParams struct {
	Body         sql.NullString `db:"body"`
	Encrypted    bool           `db:"encrypted"`
	E2eEncrypted bool           `db:"e2e_encrypted"`
	E2eeMethod   sql.NullString `db:"e2ee_method"`
	Edited       bool           `db:"edited"`
	AccountJid   string         `db:"account_jid"`
	IDAttr       sql.NullString `db:"id_attr"`
	RosterJid    sql.NullString `db:"roster_jid"`
}

// XEP-0308: apply a correction to a previously sent/received message,
// identified by its own idAttr within a given contact's history. Also used
// to opportunistically re-seal a plaintext row once a local storage
// password becomes available.
func (q *Queries) UpdateMessageBodyByID(ctx context.Context, arg UpdateMessageBodyByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMessageBodyByID,
		arg.Body,
		arg.Encrypted,
		arg.E2eEncrypted,
		arg.E2eeMethod,
		arg.Edited,
		arg.AccountJid,
		arg.IDAttr,
		arg.RosterJid,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertDiscoFeature = `-- name: UpsertDiscoFeature :one
INSERT INTO discoFeatures (var)
VALUES (?)
ON CONFLICT (var) DO UPDATE
SET var = excluded.var
RETURNING id
`

func (q *Queries) UpsertDiscoFeature(ctx context.Context, var_ string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscoFeature, var_)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDiscoIdentity = `-- name: UpsertDiscoIdentity :one
INSERT INTO discoIdentity (cat, name, typ, lang)
VALUES (?, ?, ?, ?)
ON CONFLICT (cat, name, typ, lang) DO UPDATE
SET
	cat = excluded.cat,
	name = excluded.name,
	typ = excluded.typ,
	lang = excluded.lang
RETURNING id
`

type UpsertDiscoIdentityParams struct {
	Cat  string `db:"cat"`
	Name string `db:"name"`
	Typ  string `db:"typ"`
	Lang string `db:"lang"`
}

func (q *Queries) UpsertDiscoIdentity(ctx context.Context, arg UpsertDiscoIdentityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscoIdentity,
		arg.Cat,
		arg.Name,
		arg.Typ,
		arg.Lang,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDiscoJIDCaps = `-- name: UpsertDiscoJIDCaps :exec
INSERT INTO discoJID (jid, caps)
SELECT
	?,
	entityCaps.id
FROM entityCaps
WHERE entityCaps.ver = ?
ON CONFLICT (jid) DO UPDATE
SET caps = excluded.caps
`

type UpsertDiscoJIDCapsParams struct {
	Jid string `db:"jid"`
	Ver string `db:"ver"`
}

func (q *Queries) UpsertDiscoJIDCaps(ctx context.Context, arg UpsertDiscoJIDCapsParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoJIDCaps, arg.Jid, arg.Ver)
	return err
}

const upsertDiscoJIDCapsWithForms = `-- name: UpsertDiscoJIDCapsWithForms :one
INSERT INTO discoJID (jid, caps, forms)
SELECT
	?,
	entityCaps.id,
	?
FROM entityCaps
WHERE entityCaps.ver = ?
ON CONFLICT (jid) DO UPDATE
SET
	caps = excluded.caps,
	forms = excluded.forms
RETURNING id
`

type UpsertDiscoJIDCapsWithFormsParams struct {
	Jid   string         `db:"jid"`
	Forms sql.NullString `db:"forms"`
	Ver   string         `db:"ver"`
}

func (q *Queries) UpsertDiscoJIDCapsWithForms(ctx context.Context, arg UpsertDiscoJIDCapsWithFormsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscoJIDCapsWithForms, arg.Jid, arg.Forms, arg.Ver)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertPGPPeerKey = `-- name: UpsertPGPPeerKey :exec
INSERT INTO pgpPeerKeys (accountJID, jid, fingerprint)
VALUES (?1, ?2, ?3)
ON CONFLICT (accountJID, jid) DO UPDATE
SET fingerprint = excluded.fingerprint
`

type UpsertPGPPeerKeyParams struct {
	AccountJid  string `db:"account_jid"`
	Jid         string `db:"jid"`
	Fingerprint string `db:"fingerprint"`
}

func (q *Queries) UpsertPGPPeerKey(ctx context.Context, arg UpsertPGPPeerKeyParams) error {
	_, err := q.db.ExecContext(ctx, upsertPGPPeerKey, arg.AccountJid, arg.Jid, arg.Fingerprint)
	return err
}

const upsertRoster = `-- name: UpsertRoster :exec
INSERT INTO rosterJIDs (accountJID, jid, name, subs)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(accountJID, jid) DO UPDATE
SET
	name = excluded.name,
	subs = excluded.subs
`

type UpsertRosterParams struct {
	AccountJid string `db:"account_jid"`
	Jid        string `db:"jid"`
	Name       string `db:"name"`
	Subs       string `db:"subs"`
}

func (q *Queries) UpsertRoster(ctx context.Context, arg UpsertRosterParams) error {
	_, err := q.db.ExecContext(ctx, upsertRoster,
		arg.AccountJid,
		arg.Jid,
		arg.Name,
		arg.Subs,
	)
	return err
}

const upsertRosterVersion = `-- name: UpsertRosterVersion :exec
INSERT INTO rosterVer (accountJID, ver)
VALUES (?1, ?2)
ON CONFLICT(accountJID) DO UPDATE
SET ver = excluded.ver
`

type UpsertRosterVersionParams struct {
	AccountJid string `db:"account_jid"`
	Ver        string `db:"ver"`
}

func (q *Queries) UpsertRosterVersion(ctx context.Context, arg UpsertRosterVersionParams) error {
	_, err := q.db.ExecContext(ctx, upsertRosterVersion, arg.AccountJid, arg.Ver)
	return err
}
