// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package storage

import (
	"context"
	"database/sql"
)

const deleteMessageByID = `-- name: DeleteMessageByID :execrows
DELETE FROM messages
WHERE idAttr = ?1
	AND rosterJID = ?2
`

type DeleteMessageByIDParams struct {
	IDAttr    sql.NullString `db:"id_attr"`
	RosterJid sql.NullString `db:"roster_jid"`
}

func (q *Queries) DeleteMessageByID(ctx context.Context, arg DeleteMessageByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMessageByID, arg.IDAttr, arg.RosterJid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteReactionsByReactor = `-- name: DeleteReactionsByReactor :exec
DELETE FROM messageReactions
WHERE idAttr = ?1
	AND fromJID = ?2
`

type DeleteReactionsByReactorParams struct {
	IDAttr  string `db:"id_attr"`
	FromJid string `db:"from_jid"`
}

func (q *Queries) DeleteReactionsByReactor(ctx context.Context, arg DeleteReactionsByReactorParams) error {
	_, err := q.db.ExecContext(ctx, deleteReactionsByReactor, arg.IDAttr, arg.FromJid)
	return err
}

const deleteRosterByJID = `-- name: DeleteRosterByJID :exec
DELETE FROM rosterJIDs
WHERE jid = ?
`

func (q *Queries) DeleteRosterByJID(ctx context.Context, jid string) error {
	_, err := q.db.ExecContext(ctx, deleteRosterByJID, jid)
	return err
}

const getCapsByJID = `-- name: GetCapsByJID :one
SELECT
	hash,
	ver
FROM entityCaps AS c
INNER JOIN discoJID AS j
	ON j.caps = c.id
WHERE j.jid = ?
`

type GetCapsByJIDRow struct {
	Hash string `db:"hash"`
	Ver  string `db:"ver"`
}

func (q *Queries) GetCapsByJID(ctx context.Context, jid string) (GetCapsByJIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCapsByJID, jid)
	var i GetCapsByJIDRow
	err := row.Scan(&i.Hash, &i.Ver)
	return i, err
}

const getDiscoFeaturesByJID = `-- name: GetDiscoFeaturesByJID :many
SELECT
	var
FROM discoFeatures AS f
INNER JOIN discoFeatureJID AS fj
	ON fj.feat = f.id
INNER JOIN discoJID AS j
	ON j.id = fj.jid
WHERE j.jid = ?
`

func (q *Queries) GetDiscoFeaturesByJID(ctx context.Context, jid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDiscoFeaturesByJID, jid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var var_ string
		if err := rows.Scan(&var_); err != nil {
			return nil, err
		}
		items = append(items, var_)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiscoFormsByJID = `-- name: GetDiscoFormsByJID :one
SELECT forms
FROM discoJID AS j
WHERE j.jid = ?
`

func (q *Queries) GetDiscoFormsByJID(ctx context.Context, jid string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getDiscoFormsByJID, jid)
	var forms sql.NullString
	err := row.Scan(&forms)
	return forms, err
}

const getDiscoIdentitiesByJID = `-- name: GetDiscoIdentitiesByJID :many
SELECT
	cat,
	name,
	typ,
	lang
FROM discoIdentity AS i
INNER JOIN discoIdentityJID AS ij
	ON ij.ident = i.id
INNER JOIN discoJID AS j
	ON j.id = ij.jid
WHERE j.jid = ?
`

type GetDiscoIdentitiesByJIDRow struct {
	Cat  string `db:"cat"`
	Name string `db:"name"`
	Typ  string `db:"typ"`
	Lang string `db:"lang"`
}

func (q *Queries) GetDiscoIdentitiesByJID(ctx context.Context, jid string) ([]GetDiscoIdentitiesByJIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getDiscoIdentitiesByJID, jid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDiscoIdentitiesByJIDRow
	for rows.Next() {
		var i GetDiscoIdentitiesByJIDRow
		if err := rows.Scan(
			&i.Cat,
			&i.Name,
			&i.Typ,
			&i.Lang,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRosterVersion = `-- name: GetRosterVersion :one
SELECT ver
FROM rosterVer
WHERE id = 0
`

func (q *Queries) GetRosterVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getRosterVersion)
	var ver string
	err := row.Scan(&ver)
	return ver, err
}

const getServicesByFeature = `-- name: GetServicesByFeature :many
SELECT j.jid
FROM discoJID AS j
INNER JOIN discoFeatureJID AS fj
	ON fj.jid = j.id
INNER JOIN discoFeatures AS f
	ON fj.feat = f.id
WHERE f.var = ?
`

func (q *Queries) GetServicesByFeature(ctx context.Context, var_ string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getServicesByFeature, var_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var jid string
		if err := rows.Scan(&jid); err != nil {
			return nil, err
		}
		items = append(items, jid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDiscoFeatureJID = `-- name: InsertDiscoFeatureJID :exec
INSERT INTO discoFeatureJID (jid, feat)
VALUES (?, ?)
ON CONFLICT(jid, feat) DO NOTHING
`

type InsertDiscoFeatureJIDParams struct {
	Jid  int64 `db:"jid"`
	Feat int64 `db:"feat"`
}

func (q *Queries) InsertDiscoFeatureJID(ctx context.Context, arg InsertDiscoFeatureJIDParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoFeatureJID, arg.Jid, arg.Feat)
	return err
}

const insertDiscoIdentityJID = `-- name: InsertDiscoIdentityJID :exec
INSERT INTO discoIdentityJID (jid, ident)
VALUES (?, ?)
ON CONFLICT (jid, ident) DO NOTHING
`

type InsertDiscoIdentityJIDParams struct {
	Jid   int64 `db:"jid"`
	Ident int64 `db:"ident"`
}

func (q *Queries) InsertDiscoIdentityJID(ctx context.Context, arg InsertDiscoIdentityJIDParams) error {
	_, err := q.db.ExecContext(ctx, insertDiscoIdentityJID, arg.Jid, arg.Ident)
	return err
}

const insertEntityCaps = `-- name: InsertEntityCaps :exec
INSERT INTO entityCaps (hash, ver)
VALUES (?, ?)
ON CONFLICT (hash, ver) DO NOTHING
`

type InsertEntityCapsParams struct {
	Hash string `db:"hash"`
	Ver  string `db:"ver"`
}

func (q *Queries) InsertEntityCaps(ctx context.Context, arg InsertEntityCapsParams) error {
	_, err := q.db.ExecContext(ctx, insertEntityCaps, arg.Hash, arg.Ver)
	return err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (
	sent,
	toAttr,
	fromAttr,
	idAttr,
	body,
	stanzaType,
	originID,
	delay,
	rosterJID,
	archiveID,
	replyToIdAttr
)
VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	IFNULL(
		NULLIF(?8, 0),
		CAST(strftime('%s', 'now') AS INTEGER)
	),
	?9,
	?10,
	?11
)
ON CONFLICT (originID, fromAttr) DO UPDATE
SET archiveID = excluded.archiveID
RETURNING id
`

type InsertMessageParams struct {
	Sent          bool           `db:"sent"`
	ToAttr        sql.NullString `db:"to_attr"`
	FromAttr      sql.NullString `db:"from_attr"`
	IDAttr        sql.NullString `db:"id_attr"`
	Body          sql.NullString `db:"body"`
	StanzaType    string         `db:"stanza_type"`
	OriginID      sql.NullString `db:"origin_id"`
	Delay         interface{}    `db:"delay"`
	RosterJid     sql.NullString `db:"roster_jid"`
	ArchiveID     sql.NullString `db:"archive_id"`
	ReplyToIDAttr sql.NullString `db:"reply_to_id_attr"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.Sent,
		arg.ToAttr,
		arg.FromAttr,
		arg.IDAttr,
		arg.Body,
		arg.StanzaType,
		arg.OriginID,
		arg.Delay,
		arg.RosterJid,
		arg.ArchiveID,
		arg.ReplyToIDAttr,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertReaction = `-- name: InsertReaction :exec
INSERT INTO messageReactions (idAttr, fromJID, emoji)
VALUES (?1, ?2, ?3)
ON CONFLICT (idAttr, fromJID, emoji) DO NOTHING
`

type InsertReactionParams struct {
	IDAttr  string `db:"id_attr"`
	FromJid string `db:"from_jid"`
	Emoji   string `db:"emoji"`
}

func (q *Queries) InsertReaction(ctx context.Context, arg InsertReactionParams) error {
	_, err := q.db.ExecContext(ctx, insertReaction, arg.IDAttr, arg.FromJid, arg.Emoji)
	return err
}

const insertRosterGroup = `-- name: InsertRosterGroup :exec
INSERT INTO rosterGroups (jid, name)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type InsertRosterGroupParams struct {
	Jid  string `db:"jid"`
	Name string `db:"name"`
}

func (q *Queries) InsertRosterGroup(ctx context.Context, arg InsertRosterGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertRosterGroup, arg.Jid, arg.Name)
	return err
}

const listEarliestArchiveIDs = `-- name: ListEarliestArchiveIDs :many
SELECT
	archiveID,
	MIN(delay) AS mindelay
FROM messages
WHERE rosterJID = ?
GROUP BY delay
HAVING mindelay NOT NULL
`

type ListEarliestArchiveIDsRow struct {
	Archiveid sql.NullString `db:"archiveid"`
	Mindelay  interface{}    `db:"mindelay"`
}

func (q *Queries) ListEarliestArchiveIDs(ctx context.Context, rosterjid sql.NullString) ([]ListEarliestArchiveIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEarliestArchiveIDs, rosterjid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEarliestArchiveIDsRow
	for rows.Next() {
		var i ListEarliestArchiveIDsRow
		if err := rows.Scan(&i.Archiveid, &i.Mindelay); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestArchiveIDs = `-- name: ListLatestArchiveIDs :many
SELECT
	j.jid,
	m.archiveID,
	MAX(m.delay)
FROM messages AS m
INNER JOIN rosterJIDs AS j
	ON m.rosterJID = j.jid
GROUP BY j.jid
`

type ListLatestArchiveIDsRow struct {
	Jid       string         `db:"jid"`
	Archiveid sql.NullString `db:"archiveid"`
	Max       interface{}    `db:"max"`
}

func (q *Queries) ListLatestArchiveIDs(ctx context.Context) ([]ListLatestArchiveIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestArchiveIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestArchiveIDsRow
	for rows.Next() {
		var i ListLatestArchiveIDsRow
		if err := rows.Scan(&i.Jid, &i.Archiveid, &i.Max); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByRoster = `-- name: ListMessagesByRoster :many
SELECT
	sent,
	toAttr,
	fromAttr,
	idAttr,
	body,
	stanzaType,
	delay,
	replyToIdAttr,
	retracted
FROM messages
WHERE rosterJID = ?
	AND stanzaType = COALESCE(
		NULLIF(?2, ''),
		stanzaType
	)
ORDER BY delay ASC
`

type ListMessagesByRosterParams struct {
	Rosterjid  sql.NullString `db:"rosterjid"`
	StanzaType interface{}    `db:"stanza_type"`
}

type ListMessagesByRosterRow struct {
	Sent          bool           `db:"sent"`
	Toattr        sql.NullString `db:"toattr"`
	Fromattr      sql.NullString `db:"fromattr"`
	Idattr        sql.NullString `db:"idattr"`
	Body          sql.NullString `db:"body"`
	Stanzatype    string         `db:"stanzatype"`
	Delay         int64          `db:"delay"`
	Replytoidattr sql.NullString `db:"replytoidattr"`
	Retracted     bool           `db:"retracted"`
}

func (q *Queries) ListMessagesByRoster(ctx context.Context, arg ListMessagesByRosterParams) ([]ListMessagesByRosterRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByRoster, arg.Rosterjid, arg.StanzaType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByRosterRow
	for rows.Next() {
		var i ListMessagesByRosterRow
		if err := rows.Scan(
			&i.Sent,
			&i.Toattr,
			&i.Fromattr,
			&i.Idattr,
			&i.Body,
			&i.Stanzatype,
			&i.Delay,
			&i.Replytoidattr,
			&i.Retracted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsForMessage = `-- name: ListReactionsForMessage :many
SELECT fromJID, emoji
FROM messageReactions
WHERE idAttr = ?1
`

type ListReactionsForMessageRow struct {
	Fromjid string `db:"fromjid"`
	Emoji   string `db:"emoji"`
}

func (q *Queries) ListReactionsForMessage(ctx context.Context, idAttr string) ([]ListReactionsForMessageRow, error) {
	rows, err := q.db.QueryContext(ctx, listReactionsForMessage, idAttr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReactionsForMessageRow
	for rows.Next() {
		var i ListReactionsForMessageRow
		if err := rows.Scan(&i.Fromjid, &i.Emoji); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoster = `-- name: ListRoster :many
SELECT
	jid,
	name,
	subs
FROM rosterJIDs
`

func (q *Queries) ListRoster(ctx context.Context) ([]Rosterjid, error) {
	rows, err := q.db.QueryContext(ctx, listRoster)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rosterjid
	for rows.Next() {
		var i Rosterjid
		if err := rows.Scan(&i.Jid, &i.Name, &i.Subs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageRetracted = `-- name: MarkMessageRetracted :execrows
UPDATE messages
SET retracted = TRUE
WHERE idAttr = ?1
	AND rosterJID = ?2
`

type MarkMessageRetractedParams struct {
	IDAttr    sql.NullString `db:"id_attr"`
	RosterJid sql.NullString `db:"roster_jid"`
}

func (q *Queries) MarkMessageRetracted(ctx context.Context, arg MarkMessageRetractedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMessageRetracted, arg.IDAttr, arg.RosterJid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMessagesReceived = `-- name: MarkMessagesReceived :exec
UPDATE messages
SET received = TRUE
WHERE sent = TRUE
	AND (
		idAttr = ?1
		OR originID = ?1
	)
`

func (q *Queries) MarkMessagesReceived(ctx context.Context, messageID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, markMessagesReceived, messageID)
	return err
}

const truncateRoster = `-- name: TruncateRoster :exec
DELETE FROM rosterJIDs
`

func (q *Queries) TruncateRoster(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateRoster)
	return err
}

const updateMessageBodyByID = `-- name: UpdateMessageBodyByID :execrows
UPDATE messages
SET body = ?1
WHERE idAttr = ?2
	AND rosterJID = ?3
`

type UpdateMessageBodyByIDParams struct {
	Body      sql.NullString `db:"body"`
	IDAttr    sql.NullString `db:"id_attr"`
	RosterJid sql.NullString `db:"roster_jid"`
}

// XEP-0308: apply a correction to a previously sent/received message,
// identified by its own idAttr within a given contact's history.
func (q *Queries) UpdateMessageBodyByID(ctx context.Context, arg UpdateMessageBodyByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMessageBodyByID, arg.Body, arg.IDAttr, arg.RosterJid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertDiscoFeature = `-- name: UpsertDiscoFeature :one
INSERT INTO discoFeatures (var)
VALUES (?)
ON CONFLICT (var) DO UPDATE
SET var = excluded.var
RETURNING id
`

func (q *Queries) UpsertDiscoFeature(ctx context.Context, var_ string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscoFeature, var_)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDiscoIdentity = `-- name: UpsertDiscoIdentity :one
INSERT INTO discoIdentity (cat, name, typ, lang)
VALUES (?, ?, ?, ?)
ON CONFLICT (cat, name, typ, lang) DO UPDATE
SET
	cat = excluded.cat,
	name = excluded.name,
	typ = excluded.typ,
	lang = excluded.lang
RETURNING id
`

type UpsertDiscoIdentityParams struct {
	Cat  string `db:"cat"`
	Name string `db:"name"`
	Typ  string `db:"typ"`
	Lang string `db:"lang"`
}

func (q *Queries) UpsertDiscoIdentity(ctx context.Context, arg UpsertDiscoIdentityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscoIdentity,
		arg.Cat,
		arg.Name,
		arg.Typ,
		arg.Lang,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDiscoJIDCaps = `-- name: UpsertDiscoJIDCaps :exec
INSERT INTO discoJID (jid, caps)
SELECT
	?,
	entityCaps.id
FROM entityCaps
WHERE entityCaps.ver = ?
ON CONFLICT (jid) DO UPDATE
SET caps = excluded.caps
`

type UpsertDiscoJIDCapsParams struct {
	Jid string `db:"jid"`
	Ver string `db:"ver"`
}

func (q *Queries) UpsertDiscoJIDCaps(ctx context.Context, arg UpsertDiscoJIDCapsParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoJIDCaps, arg.Jid, arg.Ver)
	return err
}

const upsertDiscoJIDCapsWithForms = `-- name: UpsertDiscoJIDCapsWithForms :one
INSERT INTO discoJID (jid, caps, forms)
SELECT
	?,
	entityCaps.id,
	?
FROM entityCaps
WHERE entityCaps.ver = ?
ON CONFLICT (jid) DO UPDATE
SET
	caps = excluded.caps,
	forms = excluded.forms
RETURNING id
`

type UpsertDiscoJIDCapsWithFormsParams struct {
	Jid   string         `db:"jid"`
	Forms sql.NullString `db:"forms"`
	Ver   string         `db:"ver"`
}

func (q *Queries) UpsertDiscoJIDCapsWithForms(ctx context.Context, arg UpsertDiscoJIDCapsWithFormsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscoJIDCapsWithForms, arg.Jid, arg.Forms, arg.Ver)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertRoster = `-- name: UpsertRoster :exec
INSERT INTO rosterJIDs (jid, name, subs)
VALUES (?, ?, ?)
ON CONFLICT(jid) DO UPDATE
SET
	name = excluded.name,
	subs = excluded.subs
`

type UpsertRosterParams struct {
	Jid  string `db:"jid"`
	Name string `db:"name"`
	Subs string `db:"subs"`
}

func (q *Queries) UpsertRoster(ctx context.Context, arg UpsertRosterParams) error {
	_, err := q.db.ExecContext(ctx, upsertRoster, arg.Jid, arg.Name, arg.Subs)
	return err
}

const upsertRosterVersion = `-- name: UpsertRosterVersion :exec
INSERT INTO rosterVer (id, ver)
VALUES (FALSE, ?)
ON CONFLICT(id) DO UPDATE
SET ver = excluded.ver
`

func (q *Queries) UpsertRosterVersion(ctx context.Context, ver string) error {
	_, err := q.db.ExecContext(ctx, upsertRosterVersion, ver)
	return err
}
