package ui

import (
	"os"
	"time"

	"charm.land/bubbles/v2/list"
	"charm.land/bubbles/v2/textarea"
	"charm.land/bubbles/v2/textinput"
	"charm.land/bubbles/v2/viewport"
	tea "charm.land/bubbletea/v2"
	"github.com/jim-ww/kage/ui/filepicker"
	zone "github.com/lrstanley/bubblezone/v2"
)

// ── Model ─────────────────────────────────────────────────────────────────────

type Model struct {
	width, height int
	termHeight    int // raw terminal rows from the last WindowSizeMsg; height is derived from this minus the footer's actual (view-dependent) row count
	selectedView
	keys   KeyMap
	theme  Theme
	styles uiStyles
	zone   *zone.Manager // owns mouse click/scroll regions marked in View(); see ui/mouse.go

	// maxMessagesPerChat caps how many messages are kept in
	// accounts[i].Messages[chatIdx] — older messages are trimmed off as new
	// ones are appended (live traffic, MAM sync) or prepended ("load
	// older"), see trimMessagesFront/trimMessagesBack in update_messages.go.
	// <= 0 means no cap.
	maxMessagesPerChat int

	// mouseEnabled gates all mouse handling: when false, MouseMode is left
	// off (no click/scroll events are generated by the terminal), zone
	// marks are skipped, and mouse-only UI elements (e.g. the send button)
	// are not drawn.
	mouseEnabled bool

	// icons selects icon glyphs for attachments/encryption instead of the
	// plain-text [tag] fallback — on only when the user's config opts in.
	icons bool

	// useGPG mirrors config's use_gpg: whether gpg encryption is available
	// at all. When off, "gpg" is hidden from the per-chat encryption picker.
	useGPG bool

	// showNames shows the sender's name in the message header instead of
	// just the «/» direction glyph.
	showNames bool

	// timeLayout is a custom Go time layout for message timestamps; empty
	// means the default ("15:04", full date for older messages depending on
	// timeOnlyToday).
	timeLayout string

	// timeOnlyToday: with the default time layout, show time-only for
	// messages sent today instead of a full date. Ignored when timeLayout
	// is set.
	timeOnlyToday bool

	// hover holds the zone ID currently under the pointer (empty if none),
	// so the currently-hovered send button/chat item/account row/message/
	// context-menu item can be highlighted. It's a pointer — shared with
	// the chat list delegate, which needs it too but only sees list.Model,
	// not Model — so a hover update via a pointer-receiver method is
	// visible everywhere without threading it through render call chains.
	hover *hoverState

	// sidebarWidthOverride is the user-dragged sidebar width (see
	// zonePaneSidebarBorder in ui/mouse.go); 0 means "not set yet, use the
	// width/4-based default computed by sidebarWidth".
	sidebarWidthOverride int
	// resizingSidebar is true from the moment the sidebar border is
	// pressed until the mouse button is released (tea.MouseReleaseMsg),
	// even if the pointer drifts off the border column mid-drag.
	resizingSidebar bool
	// sidebarHidden is true when the chat list sidebar has been toggled off
	// (Ctrl+\ or the toggle button) — sidebarWidth/chatAreaWidth collapse to
	// give the chat area the full width.
	sidebarHidden bool

	// inputHeightOverride is the user-dragged compose box height (see
	// zonePaneInput in ui/mouse.go); 0 means "not set yet, use the
	// DynamicHeight/inputMaxHeight-based default". Applied as the
	// textarea's MinHeight so it holds even when content would otherwise
	// shrink it back down.
	inputHeightOverride int
	// resizingInput is true from the moment the compose box's top border is
	// pressed until the mouse button is released (tea.MouseReleaseMsg),
	// even if the pointer drifts off the border row mid-drag.
	resizingInput bool

	accounts       []Account
	currentAccount int
	chats          list.Model

	input    textarea.Model
	viewport viewport.Model

	// draftHistory is the compose box's undo/redo stack for the current
	// session — draftHistory[draftHistIdx] is always the value currently in
	// m.input. Reset (not appended to) whenever the box's content changes for
	// a reason other than typing; see resetDraftHistory.
	draftHistory []string
	draftHistIdx int

	// openChatAccountIdx/openChatAddress identify which chat's draft is
	// currently loaded into m.input, so switching to a different chat knows
	// where to save the outgoing text and which chat's stored Draft to load
	// in. openChatAddress is "" when nothing's been loaded yet (startup,
	// before the first chat is opened). See swapComposeDraft.
	openChatAccountIdx int
	openChatAddress    string

	// draftSaveGen increments on every keystroke that changes the draft;
	// armDraftSaveTimer's pending draftSaveMsg must still match it when it
	// fires, or a later keystroke already re-armed (or the chat changed) and
	// this one is stale — mirrors typingGen/typingPauseMsg.
	draftSaveGen int

	// stashedDraft holds an in-progress new-message draft that was in the
	// compose box when the user started editing/reacting to a different
	// message (both overwrite m.input with that message's own content) — nil
	// means nothing's stashed. Restored by restoreStashedDraft once that
	// composition ends (sent or cancelled), so it isn't silently lost.
	stashedDraft *string

	// message interaction state
	selectedMsg          int               // index of highlighted message (meaningful in viewViewport)
	editingMsgIdx        int               // >= 0 while editing a message; -1 otherwise
	replyToIdx           int               // >= 0 while composing a reply; -1 otherwise
	reactingMsgIdx       int               // >= 0 while composing a reaction; -1 otherwise
	emojiSuggestions     []emojiSuggestion // live fuzzy matches for the shortcode being typed, while reactingMsgIdx >= 0
	emojiSuggestIdx      int               // which suggestion is highlighted; left/right to move, tab to accept it
	confirmTarget        confirmTarget
	contextMenu          *contextMenu // non-nil while a right-click action popup is open; see ui/contextmenu.go
	showMsgInfo          bool         // true while the message-info popup is open
	showHelp             bool         // true while the full-keybindings help popup (ctrl+?) is open
	openItems            []string     // non-empty while the open-link/attachment picker is open
	openItemsAttachCount int          // how many leading entries of openItems are real attachments (vs. a plain link found in Content) - openableItems always puts attachments first
	openPage             int          // current page (of openItemsPerPage items) in the open picker
	openMode             pickerMode   // what picking an item from openItems actually does: open or save
	filePicker           filepicker.Model
	pickingFile          bool                // true while the Bubble file picker is open
	pendingAttachments   []pendingAttachment // files staged (via the file picker) to go out with the next sent message; nothing is uploaded until send
	selectedAttachment   int                 // index into pendingAttachments highlighted for Tab/Backspace/ctrl+o; -1 when empty
	msgOffsets           []int               // line offset of each message inside viewport content
	viewportLines        []string            // viewport content split into lines, kept in sync with msgOffsets for refreshViewportSelection's line-range patching
	noticeText           string
	noticeID             int
	noticeDuration       time.Duration                      // how long a notification toast stays visible before auto-dismissing
	transferOrder        []string                           // insertion order of transfers keys, for stable multi-line rendering
	transfers            map[string]FileTransferProgressMsg // active uploads/downloads, keyed by ID (local path for an upload, URL for a download); removed once the transfer's terminal result msg arrives
	downloadsInFlight    map[string]bool                    // URLs currently being downloaded (open or save), so mashing the open/save key doesn't start a duplicate download of the same file; cleared once the terminal openResultMsg/saveResultMsg for that URL arrives

	// double-click detection for messages
	lastClickedMsgIdx int       // index of the last clicked message (for double-click detection)
	lastClickTime     time.Time // time of the last message click (for double-click detection)

	// double-click detection for the file picker
	lastFilePickerRow  int       // rendered row of the last clicked file-picker entry
	lastFilePickerTime time.Time // time of the last file-picker click

	sender                 MessageSender
	fileSender             FileSender
	accountAdder           AccountAdder
	deviceManager          OmemoDeviceManager
	contactManager         ContactManager
	renamer                ContactRenamer
	defaultAccountSetter   DefaultAccountSetter
	sidebarWidthSetter     SidebarWidthSetter
	sidebarHiddenSetter    SidebarHiddenSetter
	inputHeightSetter      InputHeightSetter
	filePickerSortSetter   FilePickerSortSetter
	chatEncryptionSetter   ChatEncryptionSetter
	lastChatSetter         LastChatSetter
	historyLoader          HistoryLoader
	accountStatusSetter    AccountStatusSetter
	accountRemover         AccountRemover
	chatReadTracker        ChatReadTracker
	draftSaver             DraftSaver
	storagePasswordChanger StoragePasswordChanger
	focusReporter          FocusReporter

	// focused tracks whether the terminal currently has OS focus, reported
	// by tea.FocusMsg/tea.BlurMsg (requires terminal support). Starts true
	// so a terminal that never sends focus events is treated as focused
	// rather than permanently suppressing notifications.
	focused bool

	// loadingOlderHistory marks chat indices with a LoadOlderHistory fetch
	// currently in flight, so scrolling/MsgUp near the top of a long history
	// doesn't fire duplicate requests while the first is still pending.
	loadingOlderHistory map[int]bool

	// pendingOpenChatAddress is the peer JID to auto-open once its owning
	// account's chats have loaded (see AccountConnectedMsg/AccountLiveMsg
	// handling), populated from config when open_last_chat is set. Cleared
	// after the first attempt, whether or not a matching chat was found.
	pendingOpenChatAddress string

	// rename-chat prompt state, active while renamingChat is true. Opened by
	// RenameChat (viewChats) or a chat-item context menu's "Rename", prefilled
	// with the chat's custom name if it has one; submitting an empty value
	// clears it (falls back to showing the JID).
	renamingChat  bool
	renameChatIdx int
	renameInput   textinput.Model

	// save-as prompt state, active while savingAs is true. Opened by
	// SaveMsgAs (Ctrl+Shift+S) or picking an item from the open/save popup
	// while openMode == pickerModeSaveAs; saveAsTarget is the URL to
	// download once a destination path is submitted.
	savingAs     bool
	saveAsTarget string
	saveAsInput  textinput.Model

	// changePasswordState is non-nil while the "change local storage
	// password" popup is open — see ui/storage_password.go.
	changePasswordState *changePasswordState

	// typingActiveTo is the address of the chat we're currently marked as
	// "composing" to (empty if not composing to anyone). typingGen
	// increments on every keystroke while composing, so a pending
	// typingPauseMsg (scheduled a few seconds out to send "stopped
	// composing" after a stall) can tell whether it's stale — a later
	// keystroke rearmed the timer — or should actually fire.
	typingActiveTo string
	typingGen      int

	// add-account form state, active while addingAccount is true
	addingAccount    bool
	addAccountInputs [3]textinput.Model // JID, password, gpg key ID (optional)
	addAccountFocus  int
	addAccountErr    string
	addAccountBusy   bool

	// deviceList is non-nil while the OMEMO device-list popup is open — see
	// ui/omemo_devices.go.
	deviceList *deviceListState

	// contactManagerState is non-nil while the "manage contacts" popup is
	// open — see ui/contacts.go.
	contactManagerState *contactManagerState
}

// DisplayOptions bundles the message-rendering config toggles.
type DisplayOptions struct {
	Icons               bool          // show icons for attachments/encryption instead of plain-text tags
	ShowNames           bool          // show the sender's name in the message header instead of just a direction glyph
	TimeLayout          string        // custom Go time layout for message timestamps; empty means the default
	TimeOnlyToday       bool          // with the default time layout, show time-only for messages sent today instead of a full date
	MaxMessagesPerChat  int           // cap on messages kept per chat in memory/view; <= 0 means no cap
	UseGPG              bool          // whether gpg encryption is available; hides "gpg" from the per-chat encryption picker when off
	NoticeDuration      time.Duration // how long an in-app notification toast stays visible; <= 0 means the default
	FilePickerDirsFirst bool          // group directories before files in the attach-file picker regardless of sort order
	// FilePickerSortField/FilePickerSortAscending seed the attach-file
	// picker's initial sort, persisted from the last selection (see
	// FilePickerSortSetter). "" (or any value other than "created")
	// resolves to updated/mtime; see filepicker.ParseSortField.
	FilePickerSortField     string
	FilePickerSortAscending bool
}

func New(accounts []Account, startAccount int, keys KeyMap, theme Theme, sender MessageSender, accountAdder AccountAdder, mouseEnabled bool, initialSidebarWidth int, initialSidebarHidden bool, openLastChatAddress string, initialInputHeight int, display DisplayOptions) Model {
	styles := newUIStyles(theme)
	zm := zone.New()
	zm.SetEnabled(mouseEnabled)
	hv := &hoverState{}
	delegate := newChatListDelegate(styles.colors, zm, mouseEnabled, hv)

	if startAccount < 0 || startAccount >= len(accounts) {
		startAccount = 0
	}
	initialChats := []list.Item(nil)
	if len(accounts) > 0 {
		initialChats = accounts[startAccount].Chats
	}
	l := list.New(initialChats, delegate, 0, 0)
	l.SetShowTitle(false)
	l.SetShowStatusBar(false)
	l.SetShowHelp(false) // superseded by the app-wide footer hint
	// The list's default keymap binds esc/q to quit the whole program —
	// we own quitting (and esc/back) ourselves via KeyMap.Quit/Back, so
	// without this, esc reaching the list while browsing (unfiltered)
	// would fall through to list.Model.Update's own Quit case.
	l.DisableQuitKeybindings()
	l.InfiniteScrolling = true
	applyChatListStyles(&l, styles.colors)

	ti := textarea.New()
	ti.Placeholder = "message..."
	ti.Prompt = "› "
	ti.ShowLineNumbers = false
	ti.KeyMap = keys.InputAreaKeys
	ti.DynamicHeight = true
	ti.MinHeight = 1
	ti.MaxHeight = inputMaxHeight
	if initialInputHeight > 0 {
		ti.MinHeight = initialInputHeight
		ti.MaxHeight = max(inputMaxHeight, initialInputHeight)
	}
	ti.Focus()
	applyTextAreaStyles(&ti, styles.colors)
	picker := filepicker.New()
	if home, err := os.UserHomeDir(); err == nil && home != "" {
		picker.CurrentDirectory = home
	}
	picker.ShowPermissions = false
	picker.DirsFirst = display.FilePickerDirsFirst
	picker.SortField = filepicker.ParseSortField(display.FilePickerSortField)
	picker.SortAscending = display.FilePickerSortAscending
	applyFilePickerStyles(&picker, styles.colors)
	fileSender, _ := sender.(FileSender)
	renamer, _ := sender.(ContactRenamer)
	defaultAccountSetter, _ := sender.(DefaultAccountSetter)
	chatEncryptionSetter, _ := sender.(ChatEncryptionSetter)
	sidebarWidthSetter, _ := sender.(SidebarWidthSetter)
	sidebarHiddenSetter, _ := sender.(SidebarHiddenSetter)
	inputHeightSetter, _ := sender.(InputHeightSetter)
	filePickerSortSetter, _ := sender.(FilePickerSortSetter)
	lastChatSetter, _ := sender.(LastChatSetter)
	chatReadTracker, _ := sender.(ChatReadTracker)
	draftSaver, _ := sender.(DraftSaver)
	storagePasswordChanger, _ := sender.(StoragePasswordChanger)
	historyLoader, _ := sender.(HistoryLoader)
	deviceManager, _ := sender.(OmemoDeviceManager)
	contactManager, _ := sender.(ContactManager)
	accountStatusSetter, _ := sender.(AccountStatusSetter)
	accountRemover, _ := sender.(AccountRemover)
	focusReporter, _ := sender.(FocusReporter)

	noticeDuration := display.NoticeDuration
	if noticeDuration <= 0 {
		noticeDuration = DefaultNoticeDuration
	}

	return Model{
		selectedView:           viewChat,
		keys:                   keys,
		theme:                  theme,
		styles:                 styles,
		zone:                   zm,
		mouseEnabled:           mouseEnabled,
		maxMessagesPerChat:     display.MaxMessagesPerChat,
		icons:                  display.Icons,
		useGPG:                 display.UseGPG,
		noticeDuration:         noticeDuration,
		showNames:              display.ShowNames,
		timeLayout:             display.TimeLayout,
		timeOnlyToday:          display.TimeOnlyToday,
		hover:                  hv,
		accounts:               accounts,
		currentAccount:         startAccount,
		chats:                  l,
		input:                  ti,
		draftHistory:           []string{""},
		viewport:               viewport.New(),
		editingMsgIdx:          -1,
		replyToIdx:             -1,
		selectedAttachment:     -1,
		reactingMsgIdx:         -1,
		lastClickedMsgIdx:      -1,
		lastFilePickerRow:      -1,
		sender:                 sender,
		fileSender:             fileSender,
		accountAdder:           accountAdder,
		deviceManager:          deviceManager,
		contactManager:         contactManager,
		renamer:                renamer,
		defaultAccountSetter:   defaultAccountSetter,
		chatEncryptionSetter:   chatEncryptionSetter,
		sidebarWidthSetter:     sidebarWidthSetter,
		sidebarHiddenSetter:    sidebarHiddenSetter,
		inputHeightSetter:      inputHeightSetter,
		filePickerSortSetter:   filePickerSortSetter,
		lastChatSetter:         lastChatSetter,
		historyLoader:          historyLoader,
		accountStatusSetter:    accountStatusSetter,
		accountRemover:         accountRemover,
		chatReadTracker:        chatReadTracker,
		draftSaver:             draftSaver,
		storagePasswordChanger: storagePasswordChanger,
		focusReporter:          focusReporter,
		focused:                true,
		openChatAccountIdx:     -1,
		loadingOlderHistory:    make(map[int]bool),
		pendingOpenChatAddress: openLastChatAddress,
		sidebarWidthOverride:   initialSidebarWidth,
		sidebarHidden:          initialSidebarHidden,
		inputHeightOverride:    initialInputHeight,
		filePicker:             picker,
	}
}

// newAddAccountForm builds fresh, empty textinput.Model fields for the
// add-account popup: JID, password (masked), and an optional GPG key ID.
// addAccountFieldWidth is fixed rather than derived from terminal size — the
// add-account popup isn't full-width like the main input box, and an unset
// (zero) textinput.Width truncates the placeholder to a single character
// (see textinput.Model.placeholderView's width-based truncation math), so
// this must be at least as wide as the longest placeholder below.
const addAccountFieldWidth = 42

// DefaultNoticeDuration is how long an in-app notification toast stays
// visible before auto-dismissing when DisplayOptions.NoticeDuration is unset.
const DefaultNoticeDuration = 3 * time.Second

func (m Model) newAddAccountForm() [3]textinput.Model {
	var fields [3]textinput.Model

	jidInput := textinput.New()
	jidInput.Placeholder = "user@server"
	jidInput.Prompt = "JID:      "
	jidInput.KeyMap = m.keys.TextInputKeys
	jidInput.SetWidth(addAccountFieldWidth)
	applyTextInputStyles(&jidInput, m.styles.colors)
	jidInput.Focus()
	fields[0] = jidInput

	passInput := textinput.New()
	passInput.Placeholder = "(leave blank to use password_cmd/keyring)"
	passInput.Prompt = "Password: "
	passInput.EchoMode = textinput.EchoPassword
	passInput.KeyMap = m.keys.TextInputKeys
	passInput.SetWidth(addAccountFieldWidth)
	applyTextInputStyles(&passInput, m.styles.colors)
	fields[1] = passInput

	gpgInput := textinput.New()
	gpgInput.Placeholder = "(optional) own gpg key fingerprint"
	gpgInput.Prompt = "GPG key:  "
	gpgInput.KeyMap = m.keys.TextInputKeys
	gpgInput.SetWidth(addAccountFieldWidth)
	applyTextInputStyles(&gpgInput, m.styles.colors)
	fields[2] = gpgInput

	return fields
}

// ── Init ──────────────────────────────────────────────────────────────────────

func (m Model) Init() tea.Cmd {
	return tea.Batch(textinput.Blink, func() tea.Msg { return openPendingChatMsg{} })
}
